version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: pdflibrary_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
    restart: unless-stopped
